@startuml
skinparam linetype ortho
hide circle

package "Decoder Module" {

    interface Decoder<O,OC,IC> {
        +decode(certificate: OC): IC
    }

    class Decoder3CGto3SAT implements Decoder
    class DecoderHCYCLEto3SAT implements Decoder
    class DecoderHCIRCUITtoHCYCLE implements Decoder
    class DecoderSSPto3SAT implements Decoder
    class DecoderTSPtoHCIRCUIT implements Decoder

}

@enduml
