@startuml
skinparam linetype ortho

package "Decoder Module" {

    interface Decoder<OC is Certificate, IC is Certificate> {
        +decode(outCert: OC): IC
    }

    class Decoder3CGto3SAT {
        +decode(outCert: Certificate3CG): Certificate3SAT
    }

    class DecoderHCYCLEto3SAT {
        +decode(outCert: CertificateHCYCLE): Certificate3SAT
    }

    class DecoderHCIRCUITtoHCYCLE {
        +decode(outCert: CertificateHCIRCUIT): CertificateHCYCLE
    }

    class DecoderSSPto3SAT {
        +decode(outCert: CertificateSSP): Certificate3SAT
    }

    class DecoderTSPtoHCIRCUIT {
        +decode(outCert: CertificateTSP): CertificateHCIRCUIT
    }

    Decoder3CGto3SAT .up.|> Decoder
    DecoderHCYCLEto3SAT .up.|> Decoder
    DecoderHCIRCUITtoHCYCLE .down.|> Decoder
    DecoderSSPto3SAT .down.|> Decoder
    DecoderTSPtoHCIRCUIT .down.|> Decoder
}

@enduml
