@startuml sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

actor Uživatel as user
participant "UI" as ui
participant "Datové struktury" as data
participant "Redukční modul" as reducer
participant "Řešící modul" as solver
participant "Dekódovací modul" as decoder

user -> ui: 1. Zadá instanci
ui -> data: 2. Převede do interní reprezentace
data -> reducer: 3. Transformuje instanci
reducer -> data: Vytvoří výstupní instanci
reducer -> data: Vytvoří kroky redukce
data -> solver: 4. Řeší výstupní instanci
alt Řešení nalezeno
  solver -> data: Vrací řešení
  data -> decoder: 5. Dekóduje řešení
  decoder -> ui: Zpět na řešení vstupního problému
else Řešení nenalezeno
  solver -> ui: Informace o neúspěchu
end

@enduml