@startuml use-case
'skinparam packageStyle rectangle
left to right direction

actor Uživatel as user

rectangle Aplikace {
  usecase UC1 as "Vybrat redukci"
  usecase UC2 as "Zadat vlastní instanci"
  usecase UC3 as "Vybrat ukázkovou instanci"
  usecase UC4 as "Spustit redukci"
  usecase UC5 as "Vizualizovat vstupní instanci"
  usecase UC6 as "Vizualizovat výstupní instanci"
  usecase UC7 as "Zobrazit kroky redukce"
  usecase UC8 as "Spustit solver (na výstupní problém)"
  usecase UC9 as "Zobrazit řešení"
  usecase UC10 as "Zobrazit dekódované řešení"
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC8
UC2 ..> UC5 : include
UC3 ..> UC5 : include
UC4 ..> UC6 : include
UC5 <.. UC7 : extend

'UC6 <.. UC8 : extend
UC8 ..> UC9 : include
UC9 <.. UC10 : extend
@enduml
